// Code generated by github.com/activatedio/gen. DO NOT EDIT.

package gorm

import (
	fx "go.uber.org/fx"

	gorm "github.com/activatedio/datainfra/pkg/data/gorm"
)

// Index collects constructors for implementations in an fx module
func Index() fx.Option {
	return fx.Module("example.data.gorm", fx.Provide(gorm.NewDB, gorm.NewContextBuilder, NewLocationRepository, NewCategoryRepository, NewProductRepository, NewThemeRepository))
}
