// Code generated by github.com/activatedio/gen. DO NOT EDIT.

package gorm

import (
	model "github.com/activatedio/datainfra/examples/data/model"
	repository "github.com/activatedio/datainfra/examples/data/repository"
	data "github.com/activatedio/datainfra/pkg/data"
	gorm "github.com/activatedio/datainfra/pkg/data/gorm"
	fx "go.uber.org/fx"
)

// TagInternal is the internal representation of Tag
type TagInternal struct {
	*model.Tag
}

// tagRepositoryImpl is the implementation of TagRepository
type tagRepositoryImpl struct {
	Template gorm.MappingTemplate[*model.Tag, *TagInternal]
	data.CrudTemplate[*model.Tag, string]
	data.FilterKeysTemplate[string]
}

// TagRepositoryParams are the parameters for TagRepository
type TagRepositoryParams struct {
	fx.In
}

// NewTagRepository creates a new TagRepository
func NewTagRepository(TagRepositoryParams) repository.TagRepository {
	template := gorm.NewMappingTemplate[*model.Tag, *TagInternal](gorm.MappingTemplateParams[*model.Tag, *TagInternal]{
		Table: "tags",
		ToInternal: func(m *model.Tag) *TagInternal {
			return &TagInternal{
				Tag: m,
			}
		},
		FromInternal: func(m *TagInternal) *model.Tag {
			return m.Tag
		},
		KeyColumns: []string{"name"},
		KeyAccessor: func(m *TagInternal) []any {
			return []any{m.Name}
		},
	})
	return &tagRepositoryImpl{
		Template: template,
		CrudTemplate: gorm.NewMappingCrudTemplate[*model.Tag, *TagInternal, string](gorm.MappingCrudTemplateImplOptions[*model.Tag, *TagInternal, string]{
			Template: template,
			FindBuilder: gorm.NewFindBuilder[string](gorm.FindPredicate[string]{
				Accessor: func(key string) any {
					return key
				},
				Column: "name",
			}),
		}),
		FilterKeysTemplate: gorm.NewMappingFilterKeysTemplate[*model.Tag, *TagInternal, string](gorm.MappingFilterKeysTemplateImplOptions[*model.Tag, *TagInternal, string]{
			Template:   template,
			FindColumn: "name",
		}),
	}
}
