// Code generated by github.com/activatedio/gen. DO NOT EDIT.

package outer

import fx "go.uber.org/fx"

// Index provides every repository's outer chain in place of the inner
// repositories, which it takes by the name "inner".
func Index() fx.Option {
	return fx.Module("example.data.outer", fx.Provide(
		NewProductRepository,
		NewTagRepository,
	))
}
