// Code generated by github.com/activatedio/gen. DO NOT EDIT.

package outer

import (
	"context"
	model "github.com/activatedio/datainfra/examples/data/model"
	repository "github.com/activatedio/datainfra/examples/data/repository"
	data "github.com/activatedio/datainfra/pkg/data"
)

// productRepositoryValidator is the validator proxy over ProductRepository.
type productRepositoryValidator struct {
	delegate repository.ProductRepository
}

// AssociateCategories implements ProductRepository.
func (r *productRepositoryValidator) AssociateCategories(p0 context.Context, p1 string, p2 []string, p3 []string) error {
	return r.delegate.AssociateCategories(p0, p1, p2, p3)
}

// AssociateTags implements ProductRepository.
func (r *productRepositoryValidator) AssociateTags(p0 context.Context, p1 string, p2 []string, p3 []string) error {
	return r.delegate.AssociateTags(p0, p1, p2, p3)
}

// Create implements ProductRepository.
func (r *productRepositoryValidator) Create(p0 context.Context, p1 *model.Product) error {
	if err := p1.Validate(); err != nil {
		return err
	}
	return r.delegate.Create(p0, p1)
}

// Delete implements ProductRepository.
func (r *productRepositoryValidator) Delete(p0 context.Context, p1 string) error {
	return r.delegate.Delete(p0, p1)
}

// DeleteEntity implements ProductRepository.
func (r *productRepositoryValidator) DeleteEntity(p0 context.Context, p1 *model.Product) error {
	return r.delegate.DeleteEntity(p0, p1)
}

// ExistsByKey implements ProductRepository.
func (r *productRepositoryValidator) ExistsByKey(p0 context.Context, p1 string) (bool, error) {
	return r.delegate.ExistsByKey(p0, p1)
}

// FindByKey implements ProductRepository.
func (r *productRepositoryValidator) FindByKey(p0 context.Context, p1 string) (*model.Product, error) {
	return r.delegate.FindByKey(p0, p1)
}

// GetSearchPredicates implements ProductRepository.
func (r *productRepositoryValidator) GetSearchPredicates(p0 context.Context) ([]*data.SearchPredicateDescriptor, error) {
	return r.delegate.GetSearchPredicates(p0)
}

// ListAll implements ProductRepository.
func (r *productRepositoryValidator) ListAll(p0 context.Context, p1 data.ListParams) (*data.List[*model.Product], error) {
	return r.delegate.ListAll(p0, p1)
}

// ListByCategory implements ProductRepository.
func (r *productRepositoryValidator) ListByCategory(p0 context.Context, p1 string, p2 data.ListParams) (*data.List[*model.Product], error) {
	return r.delegate.ListByCategory(p0, p1, p2)
}

// ListByTag implements ProductRepository.
func (r *productRepositoryValidator) ListByTag(p0 context.Context, p1 string, p2 data.ListParams) (*data.List[*model.Product], error) {
	return r.delegate.ListByTag(p0, p1, p2)
}

// Search implements ProductRepository.
func (r *productRepositoryValidator) Search(p0 context.Context, p1 []*data.SearchPredicate, p2 *data.PageParams) (*data.List[*data.SearchResult[*model.Product]], error) {
	return r.delegate.Search(p0, p1, p2)
}

// Update implements ProductRepository.
func (r *productRepositoryValidator) Update(p0 context.Context, p1 *model.Product) error {
	if err := p1.Validate(); err != nil {
		return err
	}
	return r.delegate.Update(p0, p1)
}
