// Code generated by github.com/activatedio/gen. DO NOT EDIT.

package outer

import (
	repository "github.com/activatedio/datainfra/examples/data/repository"
	outer "github.com/activatedio/datainfra/pkg/data/outer"
	fx "go.uber.org/fx"
)

// ProductRepositoryParams are the parameters of NewProductRepository.
type ProductRepositoryParams struct {
	fx.In
	Delegate repository.ProductRepository `name:"inner"`
	DiffSink outer.DiffSink               `optional:"true"`
}

// NewProductRepository is ProductRepository's outer chain over the inner repository.
func NewProductRepository(params ProductRepositoryParams) repository.ProductRepository {
	return &productRepositoryElapsed{
		delegate: &productRepositoryValidator{
			delegate: &productRepositoryDiff{
				delegate: params.Delegate,
				diffSink: outer.SinkOrDefault(params.DiffSink),
			},
		},
	}
}
