// Code generated by github.com/activatedio/gen. DO NOT EDIT.

package outer

import (
	"context"
	model "github.com/activatedio/datainfra/examples/data/model"
	repository "github.com/activatedio/datainfra/examples/data/repository"
	data "github.com/activatedio/datainfra/pkg/data"
	log "github.com/rs/zerolog/log"
	"time"
)

// productRepositoryElapsed is the elapsed proxy over ProductRepository.
type productRepositoryElapsed struct {
	delegate repository.ProductRepository
}

// AssociateCategories implements ProductRepository.
func (r *productRepositoryElapsed) AssociateCategories(p0 context.Context, p1 string, p2 []string, p3 []string) error {
	start := time.Now()
	defer func() {
		log.Debug().Str("repo", "ProductRepository").Str("method", "AssociateCategories").Dur("elapsed", time.Since(start)).Msg("repository call")
	}()
	return r.delegate.AssociateCategories(p0, p1, p2, p3)
}

// AssociateTags implements ProductRepository.
func (r *productRepositoryElapsed) AssociateTags(p0 context.Context, p1 string, p2 []string, p3 []string) error {
	start := time.Now()
	defer func() {
		log.Debug().Str("repo", "ProductRepository").Str("method", "AssociateTags").Dur("elapsed", time.Since(start)).Msg("repository call")
	}()
	return r.delegate.AssociateTags(p0, p1, p2, p3)
}

// Create implements ProductRepository.
func (r *productRepositoryElapsed) Create(p0 context.Context, p1 *model.Product) error {
	start := time.Now()
	defer func() {
		log.Debug().Str("repo", "ProductRepository").Str("method", "Create").Dur("elapsed", time.Since(start)).Msg("repository call")
	}()
	return r.delegate.Create(p0, p1)
}

// Delete implements ProductRepository.
func (r *productRepositoryElapsed) Delete(p0 context.Context, p1 string) error {
	start := time.Now()
	defer func() {
		log.Debug().Str("repo", "ProductRepository").Str("method", "Delete").Dur("elapsed", time.Since(start)).Msg("repository call")
	}()
	return r.delegate.Delete(p0, p1)
}

// DeleteEntity implements ProductRepository.
func (r *productRepositoryElapsed) DeleteEntity(p0 context.Context, p1 *model.Product) error {
	start := time.Now()
	defer func() {
		log.Debug().Str("repo", "ProductRepository").Str("method", "DeleteEntity").Dur("elapsed", time.Since(start)).Msg("repository call")
	}()
	return r.delegate.DeleteEntity(p0, p1)
}

// ExistsByKey implements ProductRepository.
func (r *productRepositoryElapsed) ExistsByKey(p0 context.Context, p1 string) (bool, error) {
	start := time.Now()
	defer func() {
		log.Debug().Str("repo", "ProductRepository").Str("method", "ExistsByKey").Dur("elapsed", time.Since(start)).Msg("repository call")
	}()
	return r.delegate.ExistsByKey(p0, p1)
}

// FindByKey implements ProductRepository.
func (r *productRepositoryElapsed) FindByKey(p0 context.Context, p1 string) (*model.Product, error) {
	start := time.Now()
	defer func() {
		log.Debug().Str("repo", "ProductRepository").Str("method", "FindByKey").Dur("elapsed", time.Since(start)).Msg("repository call")
	}()
	return r.delegate.FindByKey(p0, p1)
}

// GetSearchPredicates implements ProductRepository.
func (r *productRepositoryElapsed) GetSearchPredicates(p0 context.Context) ([]*data.SearchPredicateDescriptor, error) {
	start := time.Now()
	defer func() {
		log.Debug().Str("repo", "ProductRepository").Str("method", "GetSearchPredicates").Dur("elapsed", time.Since(start)).Msg("repository call")
	}()
	return r.delegate.GetSearchPredicates(p0)
}

// ListAll implements ProductRepository.
func (r *productRepositoryElapsed) ListAll(p0 context.Context, p1 data.ListParams) (*data.List[*model.Product], error) {
	start := time.Now()
	defer func() {
		log.Debug().Str("repo", "ProductRepository").Str("method", "ListAll").Dur("elapsed", time.Since(start)).Msg("repository call")
	}()
	return r.delegate.ListAll(p0, p1)
}

// ListByCategory implements ProductRepository.
func (r *productRepositoryElapsed) ListByCategory(p0 context.Context, p1 string, p2 data.ListParams) (*data.List[*model.Product], error) {
	start := time.Now()
	defer func() {
		log.Debug().Str("repo", "ProductRepository").Str("method", "ListByCategory").Dur("elapsed", time.Since(start)).Msg("repository call")
	}()
	return r.delegate.ListByCategory(p0, p1, p2)
}

// ListByTag implements ProductRepository.
func (r *productRepositoryElapsed) ListByTag(p0 context.Context, p1 string, p2 data.ListParams) (*data.List[*model.Product], error) {
	start := time.Now()
	defer func() {
		log.Debug().Str("repo", "ProductRepository").Str("method", "ListByTag").Dur("elapsed", time.Since(start)).Msg("repository call")
	}()
	return r.delegate.ListByTag(p0, p1, p2)
}

// Search implements ProductRepository.
func (r *productRepositoryElapsed) Search(p0 context.Context, p1 []*data.SearchPredicate, p2 *data.PageParams) (*data.List[*data.SearchResult[*model.Product]], error) {
	start := time.Now()
	defer func() {
		log.Debug().Str("repo", "ProductRepository").Str("method", "Search").Dur("elapsed", time.Since(start)).Msg("repository call")
	}()
	return r.delegate.Search(p0, p1, p2)
}

// Update implements ProductRepository.
func (r *productRepositoryElapsed) Update(p0 context.Context, p1 *model.Product) error {
	start := time.Now()
	defer func() {
		log.Debug().Str("repo", "ProductRepository").Str("method", "Update").Dur("elapsed", time.Since(start)).Msg("repository call")
	}()
	return r.delegate.Update(p0, p1)
}
