// Code generated by github.com/activatedio/gen. DO NOT EDIT.

package outer

import (
	"context"
	"fmt"
	model "github.com/activatedio/datainfra/examples/data/model"
	repository "github.com/activatedio/datainfra/examples/data/repository"
	data "github.com/activatedio/datainfra/pkg/data"
	outer "github.com/activatedio/datainfra/pkg/data/outer"
)

// productRepositoryDiff is the diff proxy over ProductRepository.
type productRepositoryDiff struct {
	delegate repository.ProductRepository
	diffSink outer.DiffSink
}

// AssociateCategories implements ProductRepository.
func (r *productRepositoryDiff) AssociateCategories(p0 context.Context, p1 string, p2 []string, p3 []string) error {
	return r.delegate.AssociateCategories(p0, p1, p2, p3)
}

// AssociateTags implements ProductRepository.
func (r *productRepositoryDiff) AssociateTags(p0 context.Context, p1 string, p2 []string, p3 []string) error {
	return r.delegate.AssociateTags(p0, p1, p2, p3)
}

// Create implements ProductRepository.
func (r *productRepositoryDiff) Create(p0 context.Context, p1 *model.Product) error {
	if err := r.delegate.Create(p0, p1); err != nil {
		return err
	}
	var existing any
	cl, err := outer.Diff(existing, p1)
	if err != nil {
		return err
	}
	return r.diffSink.Sink(p0, outer.MethodMetadata{
		Source:     "product",
		MethodName: "Create",
		TargetID:   fmt.Sprint(p1.SKU),
	}, cl)
}

// Delete implements ProductRepository.
func (r *productRepositoryDiff) Delete(p0 context.Context, p1 string) error {
	var existing any
	found, err := r.delegate.FindByKey(p0, p1)
	if err != nil {
		return err
	}
	if found != nil {
		existing = found
	}
	if err := r.delegate.Delete(p0, p1); err != nil {
		return err
	}
	if existing == nil {
		return nil
	}
	cl, err := outer.Diff(existing, nil)
	if err != nil {
		return err
	}
	return r.diffSink.Sink(p0, outer.MethodMetadata{
		Source:     "product",
		MethodName: "Delete",
		TargetID:   fmt.Sprint(p1),
	}, cl)
}

// DeleteEntity implements ProductRepository.
func (r *productRepositoryDiff) DeleteEntity(p0 context.Context, p1 *model.Product) error {
	var existing any
	found, err := r.delegate.FindByKey(p0, p1.SKU)
	if err != nil {
		return err
	}
	if found != nil {
		existing = found
	}
	if err := r.delegate.DeleteEntity(p0, p1); err != nil {
		return err
	}
	if existing == nil {
		return nil
	}
	cl, err := outer.Diff(existing, nil)
	if err != nil {
		return err
	}
	return r.diffSink.Sink(p0, outer.MethodMetadata{
		Source:     "product",
		MethodName: "DeleteEntity",
		TargetID:   fmt.Sprint(p1.SKU),
	}, cl)
}

// ExistsByKey implements ProductRepository.
func (r *productRepositoryDiff) ExistsByKey(p0 context.Context, p1 string) (bool, error) {
	return r.delegate.ExistsByKey(p0, p1)
}

// FindByKey implements ProductRepository.
func (r *productRepositoryDiff) FindByKey(p0 context.Context, p1 string) (*model.Product, error) {
	return r.delegate.FindByKey(p0, p1)
}

// GetSearchPredicates implements ProductRepository.
func (r *productRepositoryDiff) GetSearchPredicates(p0 context.Context) ([]*data.SearchPredicateDescriptor, error) {
	return r.delegate.GetSearchPredicates(p0)
}

// ListAll implements ProductRepository.
func (r *productRepositoryDiff) ListAll(p0 context.Context, p1 data.ListParams) (*data.List[*model.Product], error) {
	return r.delegate.ListAll(p0, p1)
}

// ListByCategory implements ProductRepository.
func (r *productRepositoryDiff) ListByCategory(p0 context.Context, p1 string, p2 data.ListParams) (*data.List[*model.Product], error) {
	return r.delegate.ListByCategory(p0, p1, p2)
}

// ListByTag implements ProductRepository.
func (r *productRepositoryDiff) ListByTag(p0 context.Context, p1 string, p2 data.ListParams) (*data.List[*model.Product], error) {
	return r.delegate.ListByTag(p0, p1, p2)
}

// Search implements ProductRepository.
func (r *productRepositoryDiff) Search(p0 context.Context, p1 []*data.SearchPredicate, p2 *data.PageParams) (*data.List[*data.SearchResult[*model.Product]], error) {
	return r.delegate.Search(p0, p1, p2)
}

// Update implements ProductRepository.
func (r *productRepositoryDiff) Update(p0 context.Context, p1 *model.Product) error {
	var existing any
	found, err := r.delegate.FindByKey(p0, p1.SKU)
	if err != nil {
		return err
	}
	if found != nil {
		existing = found
	}
	if err := r.delegate.Update(p0, p1); err != nil {
		return err
	}
	cl, err := outer.Diff(existing, p1)
	if err != nil {
		return err
	}
	return r.diffSink.Sink(p0, outer.MethodMetadata{
		Source:     "product",
		MethodName: "Update",
		TargetID:   fmt.Sprint(p1.SKU),
	}, cl)
}
