// Code generated by github.com/activatedio/gen. DO NOT EDIT.

package outer

import (
	"context"
	model "github.com/activatedio/datainfra/examples/data/model"
	repository "github.com/activatedio/datainfra/examples/data/repository"
	data "github.com/activatedio/datainfra/pkg/data"
)

// tagRepositoryValidator is the validator proxy over TagRepository.
type tagRepositoryValidator struct {
	delegate repository.TagRepository
}

// Create implements TagRepository.
func (r *tagRepositoryValidator) Create(p0 context.Context, p1 *model.Tag) error {
	if err := p1.Validate(); err != nil {
		return err
	}
	return r.delegate.Create(p0, p1)
}

// Delete implements TagRepository.
func (r *tagRepositoryValidator) Delete(p0 context.Context, p1 string) error {
	return r.delegate.Delete(p0, p1)
}

// DeleteEntity implements TagRepository.
func (r *tagRepositoryValidator) DeleteEntity(p0 context.Context, p1 *model.Tag) error {
	return r.delegate.DeleteEntity(p0, p1)
}

// ExistsByKey implements TagRepository.
func (r *tagRepositoryValidator) ExistsByKey(p0 context.Context, p1 string) (bool, error) {
	return r.delegate.ExistsByKey(p0, p1)
}

// FilterKeys implements TagRepository.
func (r *tagRepositoryValidator) FilterKeys(p0 context.Context, p1 []string) ([]string, error) {
	return r.delegate.FilterKeys(p0, p1)
}

// FindByKey implements TagRepository.
func (r *tagRepositoryValidator) FindByKey(p0 context.Context, p1 string) (*model.Tag, error) {
	return r.delegate.FindByKey(p0, p1)
}

// ListAll implements TagRepository.
func (r *tagRepositoryValidator) ListAll(p0 context.Context, p1 data.ListParams) (*data.List[*model.Tag], error) {
	return r.delegate.ListAll(p0, p1)
}

// Update implements TagRepository.
func (r *tagRepositoryValidator) Update(p0 context.Context, p1 *model.Tag) error {
	if err := p1.Validate(); err != nil {
		return err
	}
	return r.delegate.Update(p0, p1)
}
