// Code generated by github.com/activatedio/gen. DO NOT EDIT.

package outer

import (
	"context"
	model "github.com/activatedio/datainfra/examples/data/model"
	repository "github.com/activatedio/datainfra/examples/data/repository"
	data "github.com/activatedio/datainfra/pkg/data"
	log "github.com/rs/zerolog/log"
	"time"
)

// tagRepositoryElapsed is the elapsed proxy over TagRepository.
type tagRepositoryElapsed struct {
	delegate repository.TagRepository
}

// Create implements TagRepository.
func (r *tagRepositoryElapsed) Create(p0 context.Context, p1 *model.Tag) error {
	start := time.Now()
	defer func() {
		log.Debug().Str("repo", "TagRepository").Str("method", "Create").Dur("elapsed", time.Since(start)).Msg("repository call")
	}()
	return r.delegate.Create(p0, p1)
}

// Delete implements TagRepository.
func (r *tagRepositoryElapsed) Delete(p0 context.Context, p1 string) error {
	start := time.Now()
	defer func() {
		log.Debug().Str("repo", "TagRepository").Str("method", "Delete").Dur("elapsed", time.Since(start)).Msg("repository call")
	}()
	return r.delegate.Delete(p0, p1)
}

// DeleteEntity implements TagRepository.
func (r *tagRepositoryElapsed) DeleteEntity(p0 context.Context, p1 *model.Tag) error {
	start := time.Now()
	defer func() {
		log.Debug().Str("repo", "TagRepository").Str("method", "DeleteEntity").Dur("elapsed", time.Since(start)).Msg("repository call")
	}()
	return r.delegate.DeleteEntity(p0, p1)
}

// ExistsByKey implements TagRepository.
func (r *tagRepositoryElapsed) ExistsByKey(p0 context.Context, p1 string) (bool, error) {
	start := time.Now()
	defer func() {
		log.Debug().Str("repo", "TagRepository").Str("method", "ExistsByKey").Dur("elapsed", time.Since(start)).Msg("repository call")
	}()
	return r.delegate.ExistsByKey(p0, p1)
}

// FilterKeys implements TagRepository.
func (r *tagRepositoryElapsed) FilterKeys(p0 context.Context, p1 []string) ([]string, error) {
	start := time.Now()
	defer func() {
		log.Debug().Str("repo", "TagRepository").Str("method", "FilterKeys").Dur("elapsed", time.Since(start)).Msg("repository call")
	}()
	return r.delegate.FilterKeys(p0, p1)
}

// FindByKey implements TagRepository.
func (r *tagRepositoryElapsed) FindByKey(p0 context.Context, p1 string) (*model.Tag, error) {
	start := time.Now()
	defer func() {
		log.Debug().Str("repo", "TagRepository").Str("method", "FindByKey").Dur("elapsed", time.Since(start)).Msg("repository call")
	}()
	return r.delegate.FindByKey(p0, p1)
}

// ListAll implements TagRepository.
func (r *tagRepositoryElapsed) ListAll(p0 context.Context, p1 data.ListParams) (*data.List[*model.Tag], error) {
	start := time.Now()
	defer func() {
		log.Debug().Str("repo", "TagRepository").Str("method", "ListAll").Dur("elapsed", time.Since(start)).Msg("repository call")
	}()
	return r.delegate.ListAll(p0, p1)
}

// Update implements TagRepository.
func (r *tagRepositoryElapsed) Update(p0 context.Context, p1 *model.Tag) error {
	start := time.Now()
	defer func() {
		log.Debug().Str("repo", "TagRepository").Str("method", "Update").Dur("elapsed", time.Since(start)).Msg("repository call")
	}()
	return r.delegate.Update(p0, p1)
}
