// Code generated by github.com/activatedio/gen. DO NOT EDIT.

package outer

import (
	repository "github.com/activatedio/datainfra/examples/data/repository"
	fx "go.uber.org/fx"
)

// TagRepositoryParams are the parameters of NewTagRepository.
type TagRepositoryParams struct {
	fx.In
	Delegate repository.TagRepository `name:"inner"`
}

// NewTagRepository is TagRepository's outer chain over the inner repository.
func NewTagRepository(params TagRepositoryParams) repository.TagRepository {
	return &tagRepositoryElapsed{
		delegate: &tagRepositoryValidator{
			delegate: params.Delegate,
		},
	}
}
